# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180111_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
